version: "3.9"

networks:
  darkmoon_net:
    external: true  # mesma rede que o MongoDB

services:
  bot:
    image: python:3.12-slim
    container_name: darkmoon_bot
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app
    command: bash -c "pip install --no-cache-dir -r requirements.txt && python main.py"
    env_file:
      - .env

    networks:
      - darkmoon_net
